### ISSUE TITLE
finite time not infinite in README

### ISSUE THREAD

**Issue by klangner** [wenta/greenape#7]
IMHO in this sentence:
```
Goal of this project is to show that if we give monkey a keyboard it could write every possible function in infinite time.
```
We should have *finite time*. It can be arbitrary long but not infinite :-)

BTW it would be easier to proof this using language like Agda/Idris then Python.

**Comment by wenta** [comment]
Thanks for your message. Yes you are right, _finite_ :) 

This is a very useful advice, both of this languages looks good. When I have started thinking about this concept I have made a small research to found language with support to meta programming, but I have never met Agda or Idris. I think I will give them a chance ;)
